version: "3"

services:

  db:
    build: ./openmrs-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=openmrs
      - MYSQL_USER=openmrs
      - MYSQL_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
      - $MYSQL_INITIAL_DB_PATH:/initial-db.sql
    ports:
    - "$MYSQL_PORT:3306"

  openmrs:
    build: ./openmrs-server
    environment:
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - openmrs-data:/openmrs/data
      - $OPENMRS_WEBAPPS_PATH:/openmrs/artifacts/webapps
      - $OPENMRS_MODULES_PATH:/openmrs/artifacts/modules
    ports:
    - "$OPENMRS_SERVER_PORT:8080"
    depends_on:
      - db

volumes:
  mysql-data:
  openmrs-data:
